// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAurLo3lzE5xpM6RJ1woVej76bKB9RDVUU',
    appId: '1:894481451880:web:a1b1cb126bd0de996ea4dd',
    messagingSenderId: '894481451880',
    projectId: 'carsharev2',
    authDomain: 'carsharev2.firebaseapp.com',
    databaseURL: 'https://carsharev2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carsharev2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG93kPhaHnmgX4HuvpS0FLSRKE9KF_uS4',
    appId: '1:894481451880:android:0a1c14ffb00573366ea4dd',
    messagingSenderId: '894481451880',
    projectId: 'carsharev2',
    databaseURL: 'https://carsharev2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carsharev2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8WZPdsh4ghTXsgsjhtdThd0CCekNcRk',
    appId: '1:894481451880:ios:0283adf1b51822246ea4dd',
    messagingSenderId: '894481451880',
    projectId: 'carsharev2',
    databaseURL: 'https://carsharev2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carsharev2.appspot.com',
    iosClientId: '894481451880-icj7q7mi7erdag8u1b0migvkm0ce1n65.apps.googleusercontent.com',
    iosBundleId: 'com.example.carSharev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8WZPdsh4ghTXsgsjhtdThd0CCekNcRk',
    appId: '1:894481451880:ios:18cc4339e979399c6ea4dd',
    messagingSenderId: '894481451880',
    projectId: 'carsharev2',
    databaseURL: 'https://carsharev2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carsharev2.appspot.com',
    iosClientId: '894481451880-ki3ljrdgsfvt3hhu10qdkh1vfqau2m8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.carSharev1.RunnerTests',
  );
}
